"""empty message

Revision ID: 6e2bfc22a0e9
Revises: 87053a3f11e5
Create Date: 2020-03-31 19:21:37.911868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e2bfc22a0e9'
down_revision = '87053a3f11e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('name', sa.String(length=30), nullable=False))
    op.add_column('alert', sa.Column('petname', sa.String(length=30), nullable=False))
    op.drop_column('alert', 'lastname')
    op.drop_column('alert', 'zipcode')
    op.drop_column('alert', 'firstname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('firstname', mysql.VARCHAR(length=20), nullable=False))
    op.add_column('alert', sa.Column('zipcode', mysql.VARCHAR(length=5), nullable=False))
    op.add_column('alert', sa.Column('lastname', mysql.VARCHAR(length=20), nullable=False))
    op.drop_column('alert', 'petname')
    op.drop_column('alert', 'name')
    # ### end Alembic commands ###
