"""empty message

Revision ID: 73d72e244fb6
Revises: 8f9c25c5cd39
Create Date: 2020-03-31 21:51:02.922188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d72e244fb6'
down_revision = '8f9c25c5cd39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('image', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'image')
    # ### end Alembic commands ###
