"""empty message

Revision ID: 87053a3f11e5
Revises: 3f191fc69ed5
Create Date: 2020-03-30 18:43:08.363555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87053a3f11e5'
down_revision = '3f191fc69ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('email', sa.String(length=80), nullable=False))
    op.add_column('alert', sa.Column('firstname', sa.String(length=20), nullable=False))
    op.add_column('alert', sa.Column('lastname', sa.String(length=20), nullable=False))
    op.add_column('alert', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('alert', sa.Column('zipcode', sa.String(length=5), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert', 'zipcode')
    op.drop_column('alert', 'phone')
    op.drop_column('alert', 'lastname')
    op.drop_column('alert', 'firstname')
    op.drop_column('alert', 'email')
    # ### end Alembic commands ###
