"""empty message

Revision ID: 88808ecc19ce
Revises: 5355a9a484f4
Create Date: 2020-03-20 18:28:05.401116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88808ecc19ce'
down_revision = '5355a9a484f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('password', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'password')
    # ### end Alembic commands ###
