"""empty message

Revision ID: a33c7fb83355
Revises: cbf4b005fb7a
Create Date: 2020-03-27 15:52:47.706803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33c7fb83355'
down_revision = 'cbf4b005fb7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('image', sa.String(length=150), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet', 'image')
    # ### end Alembic commands ###
