"""empty message

Revision ID: cbf4b005fb7a
Revises: dcfaabe9e915
Create Date: 2020-03-25 17:00:59.339110

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbf4b005fb7a'
down_revision = 'dcfaabe9e915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pet', 'age',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('pet', 'breed',
               existing_type=mysql.VARCHAR(length=40),
               nullable=True)
    op.alter_column('pet', 'eyecolor',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('pet', 'furcolor',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('pet', 'gender',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('pet', 'person_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pet', 'person_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('pet', 'gender',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('pet', 'furcolor',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('pet', 'eyecolor',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.alter_column('pet', 'breed',
               existing_type=mysql.VARCHAR(length=40),
               nullable=False)
    op.alter_column('pet', 'age',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
