"""empty message

Revision ID: cf95fca77fb0
Revises: c3c95181668c
Create Date: 2020-03-25 13:59:10.085824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf95fca77fb0'
down_revision = 'c3c95181668c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert', 'person_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_index('date', table_name='alert')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('date', 'alert', ['date'], unique=True)
    op.alter_column('alert', 'person_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
